"""Core runtime-manifest generation and Docs compatibility regressions."""
import hashlib
import importlib.util
import inspect
import json
from pathlib import Path
import subprocess
import sys
from types import ModuleType, SimpleNamespace

import jsonschema
import pytest
from wrangles.utils import catalog_identity

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_SCHEMA_PATH = ROOT / "schema/wrangles-runtime-manifest.schema.json"
spec = importlib.util.spec_from_file_location("manifest_under_test", ROOT / "schema/generate_wrangle_manifest.py")
exporter = importlib.util.module_from_spec(spec)
spec.loader.exec_module(exporter)
DOCS_CONTRACTS = json.loads((ROOT / "tests/fixtures/runtime_manifest/docs-v0.1-contracts.json").read_text(encoding="utf-8"))
REVISION = "a" * 40


def operation(df, input: str, output=None, *, enabled=True):
    """type: object
    properties:
      input:
        type: string
    """
    raise AssertionError("Export must never execute the operation")


def namespace(**operations):
    result = ModuleType("fixture_runtime")
    result.__dict__.update(operations)
    return result


def configuration(**overrides):
    return SimpleNamespace(**{
        "reserved_word_replacements": {}, "where_not_implemented": [],
        "where_overwrite_output": [], **overrides,
    })


def manifest(root=None, config=None):
    return exporter.build_manifest(root=root or namespace(sample=operation), config=config or configuration(), source_version="1.20.4", source_revision=REVISION)


@pytest.fixture
def provenance(monkeypatch, tmp_path):
    (tmp_path / "setup.py").write_text("from setuptools import setup\nsetup(version='1.20.4')\n", encoding="utf-8")
    state = {"head": REVISION, "tag": REVISION, "dirty": "", "calls": []}

    def git(root, *args):
        assert root == tmp_path
        state["calls"].append(args)
        if args[0] == "status":
            return state["dirty"]
        return state["head"] if args[-1] == "HEAD" else state["tag"]

    monkeypatch.setattr(exporter, "git", git)
    return tmp_path, state


def _entry(manifest, runtime_key):
    return next(
        entry for entry in manifest["wrangles"] if entry["runtime_key"] == runtime_key
    )


def test_runtime_manifest_is_deterministic_and_schema_valid():
    first = exporter.build_manifest(source_revision="a" * 40)
    second = exporter.build_manifest(source_revision="a" * 40)

    assert exporter.manifest_json(first) == exporter.manifest_json(second)
    assert first["entry_count"] == len(first["wrangles"])
    assert [entry["runtime_key"] for entry in first["wrangles"]] == sorted(
        entry["runtime_key"] for entry in first["wrangles"]
    )

    schema = json.loads(MANIFEST_SCHEMA_PATH.read_text(encoding="utf-8"))
    jsonschema.Draft202012Validator(schema).validate(first)


def test_runtime_manifest_preserves_signature_and_embedded_schema_separately():
    manifest = exporter.build_manifest(source_revision="a" * 40)
    entry = _entry(manifest, "convert.case")
    parameters = {parameter["name"]: parameter for parameter in entry["parameters"]}

    assert entry["python_symbol"] == "wrangles.recipe_wrangles.convert.case"
    assert entry["internal_parameters"] == ["df"]
    assert parameters["input"]["required"] is True
    assert parameters["case"]["required"] is False
    assert parameters["case"]["default"] == "lower"
    assert entry["docstring_schema"]["required"] == ["input", "case"]
    assert entry["capabilities"] == {
        "if": True,
        "where": True,
        "where_params": True,
    }


@pytest.mark.parametrize("expected", DOCS_CONTRACTS["contracts"], ids=lambda entry: entry["runtime_key"])
def test_runtime_contract_matches_pinned_docs_contract(expected):
    from wrangles import config, recipe, utils

    key = expected["runtime_key"]
    function = utils.get_nested_function(config.reserved_word_replacements.get(key, key), recipe._recipe_wrangles)
    # Golden values are copied from the independent Docs snapshot, not generated by this implementation.
    assert exporter._wrangle_contract(key, function, config) == expected


def test_original_output_file_cli_and_artifact_bundle_have_identical_content(monkeypatch, tmp_path, capsys):
    manifest = exporter.build_manifest(source_revision="a" * 40)
    calls = []

    def export_checkout(**kwargs):
        calls.append(kwargs)
        return manifest

    monkeypatch.setattr(exporter, "export_checkout", export_checkout)
    legacy = tmp_path / "wrangle_runtime_manifest.json"
    exporter.main(["--output", str(legacy), "--source-revision", "a" * 40])
    file_summary = json.loads(capsys.readouterr().out)
    exporter.main(["--artifact-dir", str(tmp_path / "artifacts"), "--source-revision", "a" * 40])
    bundle_summary = json.loads(capsys.readouterr().out)
    content = (tmp_path / "artifacts" / exporter.FILENAME).read_bytes()
    assert legacy.read_bytes() == content
    assert file_summary["sha256"] == bundle_summary["sha256"]
    assert file_summary["source"] == bundle_summary["source"] == manifest["source"]
    assert calls == [{"tag": None, "expected_revision": "a" * 40, "allow_dirty": False}] * 2
    assert (tmp_path / "artifacts" / (exporter.FILENAME + ".sha256")).read_text().split()[0] == file_summary["sha256"]


def test_real_runtime_export_resolves_all_keys_without_service_calls(monkeypatch):
    import requests
    from wrangles import recipe, config, utils

    def forbidden(*args, **kwargs):
        pytest.fail("Export attempted a network request")

    monkeypatch.setattr(requests.sessions.Session, "request", forbidden)
    value = exporter.build_manifest(root=recipe._recipe_wrangles, config=config, source_version="1.20.4", source_revision=REVISION)
    entries = {entry["runtime_key"]: entry for entry in value["wrangles"]}
    assert {"lookup", "standardize", "standardize.clean", "standardize.custom", "try", "convert.parse", "math", "maths"} <= entries.keys()
    assert not any(key.startswith(("pandas.", "main.", "custom.")) for key in entries)
    for key, entry in entries.items():
        function = utils.get_nested_function(config.reserved_word_replacements.get(key, key), recipe._recipe_wrangles)
        assert entry["python_symbol"] == f"{function.__module__}.{function.__qualname__}"
        assert {parameter["name"] for parameter in entry["parameters"]} | set(entry["internal_parameters"]) | {
            name for name in entry["variadic"].values() if name is not None
        } == set(inspect.signature(function).parameters)
    sentinel = next(parameter for parameter in entries["convert.parse"]["parameters"] if parameter["name"] == "default")
    assert sentinel == {"name": "default", "kind": "positional_or_keyword", "required": False}
    assert "wrangles.recipe_wrangles.convert._DEFAULT_NOT_SET" in entries["convert.parse"]["signature"]


def test_exported_legacy_alias_still_executes_through_the_real_recipe_dispatcher():
    import pandas as pd
    from wrangles import recipe, config

    entries = {entry["runtime_key"]: entry for entry in
               exporter.build_manifest(root=recipe._recipe_wrangles, config=config, source_version="1.20.4", source_revision=REVISION)["wrangles"]}
    assert entries["math"]["parameters"] == entries["maths"]["parameters"]
    data = pd.DataFrame({"quantity": [2, 3, 0], "price": [5, 7, 8]})
    results = [recipe.run({"wrangles": [{key: {"input": "quantity * price", "output": "total"}}]},
                          dataframe=data.copy()) for key in ("math", "maths")]
    pd.testing.assert_frame_equal(results[0], results[1])
    assert results[0]["total"].tolist() == [10, 21, 0]


def test_docstrings_preserve_schema_or_plain_text_without_guessing():
    def plain(df):
        """Deprecated - use math"""

    entries = {entry["runtime_key"]: entry for entry in manifest(namespace(schema=operation, plain=plain))["wrangles"]}
    assert entries["schema"]["docstring_schema"] == {"type": "object", "properties": {"input": {"type": "string"}}}
    assert entries["schema"]["plain_docstring"] is None
    assert entries["plain"]["docstring_schema"] is None
    assert entries["plain"]["docstring_schema_status"] == "missing"
    assert entries["plain"]["plain_docstring"] == "Deprecated - use math"
    plain.__doc__ = "Notes: [literal brackets"
    assert manifest(namespace(plain=plain))["wrangles"][0]["plain_docstring"] == plain.__doc__
    plain.__doc__ = "type: [unfinished"
    with pytest.raises(ValueError, match="plain has an invalid JSON Schema docstring"):
        manifest(namespace(plain=plain))


def test_duplicate_catalog_identity_is_not_silently_assigned_to_an_alias():
    @catalog_identity("101")
    def sample(df):
        pass

    with pytest.raises(ValueError, match="duplicate catalog identity"):
        manifest(namespace(new=sample, old=sample))
    with pytest.raises(TypeError, match="callable"):
        catalog_identity("101")(object())


def test_provenance_checks_package_tag_commit_and_clean_inputs(provenance):
    root, state = provenance
    assert exporter.read_provenance(root, "v1.20.4", REVISION) == ("1.20.4", REVISION)
    assert ("rev-parse", "--verify", "refs/tags/v1.20.4^{commit}") in state["calls"]
    assert state["calls"][-1][:4] == ("status", "--porcelain", "--untracked-files=normal", "--")


def test_dirty_preview_cannot_be_exported_as_a_release(provenance):
    root, state = provenance
    state["dirty"] = " M wrangles/recipe.py"
    assert exporter.read_provenance(root, allow_dirty=True) == ("1.20.4", REVISION)
    with pytest.raises(ValueError, match="dirty release exports are forbidden"):
        exporter.read_provenance(root, "v1.20.4", allow_dirty=True)
    (root / "setup.py").write_text("setup(version=compute_version())\n", encoding="utf-8")
    with pytest.raises(ValueError, match="literal stable version"):
        exporter.read_provenance(root, allow_dirty=True)


def test_cli_exports_checkout_and_rejects_a_missing_source_tree(tmp_path):
    # The existing test-container job deliberately removes the source tree to
    # test the installed package and has no Git executable. Reject that input
    # before attempting to read its provenance.
    has_source = (exporter.ROOT / "wrangles/__init__.py").is_file()
    revision_args = []
    if has_source:
        revision = exporter.git(exporter.ROOT, "rev-parse", "HEAD")
        revision_args = ["--revision", revision]
    result = subprocess.run([sys.executable, str(exporter.ROOT / "schema/generate_wrangle_manifest.py"),
                             "--allow-dirty", *revision_args, "--artifact-dir", str(tmp_path)],
                            cwd=exporter.ROOT, capture_output=True, text=True)
    if not has_source:
        assert result.returncode == 1
        assert "has no WranglesPY source tree" in result.stderr
        assert not (tmp_path / exporter.FILENAME).exists()
        return
    assert result.returncode == 0, result.stderr
    summary = json.loads(result.stdout)
    value = json.loads((tmp_path / exporter.FILENAME).read_bytes())
    assert summary["source"] == value["source"]
    assert value["source"]["revision"] == revision
    assert value["source"]["repository"] == exporter.REPOSITORY
    assert summary["entry_count"] == len(value["wrangles"])
    assert summary["sha256"] == hashlib.sha256((tmp_path / exporter.FILENAME).read_bytes()).hexdigest()


def test_catalog_identity_survives_move_rename_and_legacy_execution():
    identity = "9223372036854775807"
    @catalog_identity(identity)
    def original(df, input):
        return input.upper()

    before = manifest(namespace(old=original))["wrangles"][0]
    original.__module__ = "wrangles.recipe_wrangles.moved"
    original.__qualname__ = "renamed"

    def old(df, input):
        return original(df, input)

    after = {entry["runtime_key"]: entry for entry in manifest(namespace(new=original, old=old))["wrangles"]}
    assert before["catalog_id"] == after["new"]["catalog_id"] == identity
    assert after["new"]["python_symbol"] == "wrangles.recipe_wrangles.moved.renamed"
    assert "catalog_id" not in after["old"]
    assert old(None, "bolt") == original(None, "bolt") == "BOLT"
    assert catalog_identity(identity)(original) is original
    with pytest.raises(ValueError, match="cannot be reassigned"):
        catalog_identity("2" if identity != "2" else "3")(original)


@pytest.mark.parametrize("identity", [101, "9223372036854775808"])
def test_catalog_identity_rejects_noncanonical_or_out_of_range_ids(identity):
    with pytest.raises(ValueError, match="BIGINT decimal string"):
        catalog_identity(identity)


@pytest.mark.parametrize("changed,tag,expected,error", [
    ({}, "v1.20.3", REVISION, "tag must match package version"),
    ({"tag": "b" * 40}, "v1.20.4", REVISION, "tag does not point"),
    ({}, "v1.20.4", "b" * 40, "expected commit"),
    ({"dirty": " M wrangles/recipe.py"}, "v1.20.4", REVISION, "inputs are dirty"),
])
def test_invalid_release_provenance_fails(provenance, changed, tag, expected, error):
    root, state = provenance
    state.update(changed)
    with pytest.raises(ValueError, match=error):
        exporter.read_provenance(root, tag, expected)
