name: 🐍 Check Docstring Sync

on:
  push:
    branches:
      # This check only runs on your protected branch.
      # ⬇️ IMPORTANT: Change 'develop' if your branch is named differently.
      - main
      # This line prevents the check from running on the temporary doc branches.
      - '!docs/**'

jobs:
  validate-docstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Generate a temporary docs YAML
        run: |
          cp docstrings.yaml original_docstrings.yaml
          python3 extract_docs.py
          mv docstrings.yaml generated_docstrings.yaml

      - name: Compare generated YAML with the one in the repo
        run: |
          echo "Comparing checked-in docstrings with freshly generated ones..."
          diff original_docstrings.yaml generated_docstrings.yaml
          echo "✅ Docstrings are in sync."